sonar.projectKey=wannasingh-portfolio
sonar.projectName=wannasingh-portfolio
sonar.projectVersion=1.0

# Paths to source code
sonar.sources=src
# Exclude third-party libraries, build output, etc.
sonar.exclusions=node_modules/**, .next/**, out/**, coverage/**

# Integration with ESLint report
sonar.eslint.reportPaths=eslint-report.json

# Default host
sonar.host.url=http://localhost:9000

# File encoding
sonar.sourceEncoding=UTF-8
